### ISSUE TITLE
A New Request

### ISSUE THREAD

**Issue by EnderLight3336** [RelativoBR/Supreme#10]
I think you can replace  "experience_bottel" in “Mob Collector"with "Flask of Knowledge" ,because it will be more useful，thanks

**Comment by RelativoBR** [comment]
accepted suggestion will be adjusted

**Comment by RelativoBR** [comment]
just confirming, suggestion is to see with the Slimefun EXP bottle filled **FILLED_FLASK_OF_KNOWLEDGE** not **FLASK_OF_KNOWLEDGE**

**Comment by MonkeyProgrammer1** [comment]
yes,it is FILLED_FLADK_OF_KNOWLEDGE,thanks

**Comment by MonkeyProgrammer1** [comment]
By the way,there is a bug on   [https://github.com/RelativoBR/Supreme/blob/main/src/main/java/com/github/relativobr/supreme/machine/MobCollector.java](url)    ,and ybw0014 fixed bug successfully  [https://github.com/SlimefunGuguProject/Supreme/commit/95c4266dc87855c7a3d5db168ddf39f067b59d67](url),this bug will cause  some **MobCollector** collect **ink_sac** instead of **glow_ink_sac** when the **glow_squid** near the machine

**Comment by RelativoBR** [comment]
fix in release v1.4.0
